"""add moving average columns to daily_price

Revision ID: 0490c61f856c
Revises: 584b35a1268e
Create Date: 2025-08-17 05:58:21.225284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0490c61f856c'
down_revision: Union[str, Sequence[str], None] = '584b35a1268e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_price', sa.Column('ma_50', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('ma_150', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('ma_200', sa.Float(), nullable=True))
    op.create_index(op.f('ix_daily_price_ma_150'), 'daily_price', ['ma_150'], unique=False)
    op.create_index(op.f('ix_daily_price_ma_200'), 'daily_price', ['ma_200'], unique=False)
    op.create_index(op.f('ix_daily_price_ma_50'), 'daily_price', ['ma_50'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_price_ma_50'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_ma_200'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_ma_150'), table_name='daily_price')
    op.drop_column('daily_price', 'ma_200')
    op.drop_column('daily_price', 'ma_150')
    op.drop_column('daily_price', 'ma_50')
    # ### end Alembic commands ###
