"""daily_price value added

Revision ID: 1fba6af8eed1
Revises: e7cad7282778
Create Date: 2025-08-16 12:35:55.401114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fba6af8eed1'
down_revision: Union[str, Sequence[str], None] = 'e7cad7282778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_price', sa.Column('value', sa.Float(), nullable=True))
    op.alter_column('daily_price', 'volume',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_daily_price_value'), 'daily_price', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_price_value'), table_name='daily_price')
    op.alter_column('daily_price', 'volume',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('daily_price', 'value')
    # ### end Alembic commands ###
