"""add_extended_analysis_fields_to_daily_price

Revision ID: 392d670a00c3
Revises: 0490c61f856c
Create Date: 2025-08-31 12:02:55.323990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392d670a00c3'
down_revision: Union[str, Sequence[str], None] = '0490c61f856c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_price', sa.Column('ma_200_20d_ago', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('is_ma_200_bullish', sa.Boolean(), nullable=True))
    op.add_column('daily_price', sa.Column('week_52_high', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('is_near_52w_high', sa.Boolean(), nullable=True))
    op.add_column('daily_price', sa.Column('week_52_low', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('is_above_52w_low', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_daily_price_is_above_52w_low'), 'daily_price', ['is_above_52w_low'], unique=False)
    op.create_index(op.f('ix_daily_price_is_ma_200_bullish'), 'daily_price', ['is_ma_200_bullish'], unique=False)
    op.create_index(op.f('ix_daily_price_is_near_52w_high'), 'daily_price', ['is_near_52w_high'], unique=False)
    op.create_index(op.f('ix_daily_price_ma_200_20d_ago'), 'daily_price', ['ma_200_20d_ago'], unique=False)
    op.create_index(op.f('ix_daily_price_week_52_high'), 'daily_price', ['week_52_high'], unique=False)
    op.create_index(op.f('ix_daily_price_week_52_low'), 'daily_price', ['week_52_low'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_price_week_52_low'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_week_52_high'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_ma_200_20d_ago'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_is_near_52w_high'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_is_ma_200_bullish'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_is_above_52w_low'), table_name='daily_price')
    op.drop_column('daily_price', 'is_above_52w_low')
    op.drop_column('daily_price', 'week_52_low')
    op.drop_column('daily_price', 'is_near_52w_high')
    op.drop_column('daily_price', 'week_52_high')
    op.drop_column('daily_price', 'is_ma_200_bullish')
    op.drop_column('daily_price', 'ma_200_20d_ago')
    # ### end Alembic commands ###
