"""add unique constraint for stock_id and date in daily_price

Revision ID: 584b35a1268e
Revises: 1fba6af8eed1
Create Date: 2025-08-16 22:17:19.651576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584b35a1268e'
down_revision: Union[str, Sequence[str], None] = '1fba6af8eed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_stock_date', 'daily_price', ['stock_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_stock_date', 'daily_price', type_='unique')
    # ### end Alembic commands ###
