"""Adjust dailyprice model table name

Revision ID: 980f8bb9caf2
Revises: e371111c46aa
Create Date: 2025-08-16 11:03:48.786875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980f8bb9caf2'
down_revision: Union[str, Sequence[str], None] = 'e371111c46aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
