"""add_relative_strength_fields_to_daily_price

Revision ID: a0a0eea4b51b
Revises: 392d670a00c3
Create Date: 2025-08-31 12:39:44.582480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a0eea4b51b'
down_revision: Union[str, Sequence[str], None] = '392d670a00c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_price', sa.Column('roc_252', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('roc_126', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('roc_63', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('roc_21', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('rs_momentum', sa.Float(), nullable=True))
    op.add_column('daily_price', sa.Column('rs_rank', sa.Integer(), nullable=True))
    op.add_column('daily_price', sa.Column('rs_grade', sa.Float(), nullable=True))
    op.create_index(op.f('ix_daily_price_roc_126'), 'daily_price', ['roc_126'], unique=False)
    op.create_index(op.f('ix_daily_price_roc_21'), 'daily_price', ['roc_21'], unique=False)
    op.create_index(op.f('ix_daily_price_roc_252'), 'daily_price', ['roc_252'], unique=False)
    op.create_index(op.f('ix_daily_price_roc_63'), 'daily_price', ['roc_63'], unique=False)
    op.create_index(op.f('ix_daily_price_rs_grade'), 'daily_price', ['rs_grade'], unique=False)
    op.create_index(op.f('ix_daily_price_rs_momentum'), 'daily_price', ['rs_momentum'], unique=False)
    op.create_index(op.f('ix_daily_price_rs_rank'), 'daily_price', ['rs_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_price_rs_rank'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_rs_momentum'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_rs_grade'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_roc_63'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_roc_252'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_roc_21'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_roc_126'), table_name='daily_price')
    op.drop_column('daily_price', 'rs_grade')
    op.drop_column('daily_price', 'rs_rank')
    op.drop_column('daily_price', 'rs_momentum')
    op.drop_column('daily_price', 'roc_21')
    op.drop_column('daily_price', 'roc_63')
    op.drop_column('daily_price', 'roc_126')
    op.drop_column('daily_price', 'roc_252')
    # ### end Alembic commands ###
