"""Add daily prices and stock.dart_code

Revision ID: e371111c46aa
Revises: 4e55a8b046a1
Create Date: 2025-08-16 10:58:39.441708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e371111c46aa'
down_revision: Union[str, Sequence[str], None] = '4e55a8b046a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_price_close'), 'daily_price', ['close'], unique=False)
    op.create_index(op.f('ix_daily_price_date'), 'daily_price', ['date'], unique=False)
    op.create_index(op.f('ix_daily_price_high'), 'daily_price', ['high'], unique=False)
    op.create_index(op.f('ix_daily_price_id'), 'daily_price', ['id'], unique=False)
    op.create_index(op.f('ix_daily_price_low'), 'daily_price', ['low'], unique=False)
    op.create_index(op.f('ix_daily_price_open'), 'daily_price', ['open'], unique=False)
    op.create_index(op.f('ix_daily_price_volume'), 'daily_price', ['volume'], unique=False)
    op.add_column('stocks', sa.Column('dart_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_stocks_dart_code'), 'stocks', ['dart_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_dart_code'), table_name='stocks')
    op.drop_column('stocks', 'dart_code')
    op.drop_index(op.f('ix_daily_price_volume'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_open'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_low'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_id'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_high'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_date'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_close'), table_name='daily_price')
    op.drop_table('daily_price')
    # ### end Alembic commands ###
