"""Add sector field to Stock model

Revision ID: e7cad7282778
Revises: b7cbc9959554
Create Date: 2025-08-16 12:28:56.102085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7cad7282778'
down_revision: Union[str, Sequence[str], None] = 'b7cbc9959554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stocks', 'market',
               existing_type=postgresql.ENUM('KOSPI', 'KOSDAQ', name='market'),
               nullable=False)
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_stocks_dart_code'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=True)
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.drop_column('stocks', 'dart_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('dart_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=False)
    op.drop_index(op.f('ix_stocks_name'), table_name='stocks')
    op.create_index(op.f('ix_stocks_name'), 'stocks', ['name'], unique=False)
    op.create_index(op.f('ix_stocks_dart_code'), 'stocks', ['dart_code'], unique=False)
    op.alter_column('stocks', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stocks', 'market',
               existing_type=postgresql.ENUM('KOSPI', 'KOSDAQ', name='market'),
               nullable=True)
    op.alter_column('stocks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
